services:
    # PHP-FPM Application Service
    app:
        build: .
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        user: "www-data"
        volumes:
            - .:/var/www
        networks:
            - laravel
        depends_on:
            - db
        environment:
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}

    # Nginx Service
    webserver:
        image: nginx:alpine
        container_name: laravel_webserver
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./.docker/nginx:/etc/nginx/conf.d
        networks:
            - laravel
        depends_on:
            - app

    # MySQL Service
    db:
        image: mysql:8.0
        container_name: laravel_db
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            timeout: 5s
            retries: 10

    # Node.js Service
    node:
        image: node:20
        container_name: laravel_node
        restart: unless-stopped
        user: "1000:1000"
        working_dir: /var/www
        volumes:
            - .:/var/www:z
        command: sh -c "mkdir -p /home/node/.npm && chown -R 1000:1000 /home/node/.npm && npm install && npx vite --host"
        ports:
          - "5173:5173" 
        networks:
            - laravel
        depends_on:
            - app

volumes:
    dbdata:
        driver: local

networks:
    laravel:
        driver: bridge
